Update CMakelists, remove git submodule command and updated README
intel/compile-time-init-build pull request #123
Opened 2022-09-12 15:46 UTC by siauthun

1. Update CMakelists -Added new lib/CMakeList.txt
2. Remove git submodule command in root's CMakeList
3. Updated README on user have to manually perform git submodule when using cib as a standalone project

2022-09-12 19:48 UTC, lukevalenty requested changes

2022-09-12 19:48 UTC, lukevalenty commented on .gitmodules
> -[submodule "lib/Catch2"]
we need to keep the .gitmodules file, no need to remove it

2022-09-12 19:48 UTC, lukevalenty commented on README.md
> +git submodule add https://github.com/catchorg/Catch2.git lib/Catch2
we don't want them to add the git submodules themselves, the .gitmodules file contains this information already. instead they can run the following command:

```shell
git submodule update --recursive
```
```

2022-09-12 19:49 UTC, lukevalenty commented
the unit tests will also need to pass before merging :)

2022-09-13 01:24 UTC, siauthun commented
Screw up the commits. Unable to revert deleted lib/Catch2 and lib/fmt. Will create another pull request

2022-09-13 01:24 UTC, closed without merging