examples added
intel/compile-time-init-build pull request #223
Opened 2022-11-23 16:00 UTC by bvbasavaraju

While going though the library, I wanted to practice with the trial and error. So, I used the same examples what was mentioned in read me file but as a build-able project with some small tweaks for my better understanding.

I followed the guidelines as suggested, please let me know if I have missed anything! 

I was not sure if the branch should be feature or bugfix. for sure it was not a bugfix. So, i selected feature even though it is just an example. I hope that is fine.

2022-11-28 18:29 UTC, lukevalenty commented
> @lukevalenty : one question related to code style!
> 
> 
> 
> I used clang-format tool to format the code. is there any recommendation!? 
> 
> 
> 
> Also, struct name has to be snake_case only!? I saw MainLoop component in CamelCase! Could you please help me understand?

Hi @bvbasavaraju! Thanks for the pull request. :) 

There are some differences in how clang-format works from one version to the next. Right now we are stuck on version 11. You'll need to make sure to run clang-format with that specific version.

We previously used CamelCase for our type names and are now using snake_case only. Their might be some outliers in documentation or comments that haven't been updated yet. 😬

2022-11-29 13:23 UTC, bvbasavaraju commented
> 

Hi @lukevalenty ,

thank you for the update. I used the clang-format version "14.0.6" and I can see that "[quality_checks_pass](https://github.com/intel/compile-time-init-build/actions/runs/3574425708/jobs/6009675030)" has been passed for the style.

Could you please let me know if I still need to rerun with clang-format version 11 and update my PR if it is required!?

Thank you.

2022-11-29 14:31 UTC, elbeno commented
@bvbasavaraju If the quality checks passed that is all good, no need to re-run with clang-format-11.  Minor changes are possible between clang-format versions, often on newer C++ features as clang-format learns to format them better. But in this case it seems 11 and 14 agree. Thanks for the contribution!

2022-11-29 16:49 UTC, lukevalenty requested changes
thanks for your pull request, these are some helpful examples for people looking to see how to use the framework. :)

i'm requesting a minor change to the code comment grammar, just replace `!!` with `.` and we should be good to merge this :)

2022-11-29 16:49 UTC, lukevalenty commented on examples/cib_serial_port/main.cpp
> +// declaration!!
suggestion: reserve exclamation marks `!` for critically important things so they stand out. nearly every sentence should end in a period `.`

2022-11-29 16:49 UTC, lukevalenty commented on examples/cib_serial_port/main.cpp
> +            std::cout << "From CoreComponent: " << byte << std::endl;
suggest: update the names of compoments in strings to match their snake_case name

2022-11-30 14:03 UTC, bvbasavaraju commented on examples/cib_serial_port/main.cpp
> +// declaration!!
Thank you for the input. I have updated the same.

2022-11-30 14:04 UTC, bvbasavaraju commented on examples/cib_serial_port/main.cpp
> +            std::cout << "From CoreComponent: " << byte << std::endl;
Thank you for the suggestion. I have replaced with the snake_case name.

2022-11-30 14:05 UTC, bvbasavaraju commented
> @bvbasavaraju If the quality checks passed that is all good, no need to re-run with clang-format-11. Minor changes are possible between clang-format versions, often on newer C++ features as clang-format learns to format them better. But in this case it seems 11 and 14 agree. Thanks for the contribution!

@elbeno thank you for the guidance.

2022-11-30 14:06 UTC, bvbasavaraju commented
> thanks for your pull request, these are some helpful examples for people looking to see how to use the framework. :)
> 
> i'm requesting a minor change to the code comment grammar, just replace `!!` with `.` and we should be good to merge this :)

@lukevalenty I have worked on review comment and suggestion. Please let me know if additional changes are needed

2022-11-30 16:44 UTC, lukevalenty approved these changes
looks good :)

2022-11-30 16:56 UTC, bvbasavaraju commented
> looks good :)

Sure thank you.

2022-11-30 17:00 UTC, merged