add runtime_conditional and flow unary operator+
intel/compile-time-init-build pull request #606
Opened 2024-08-28 18:47 UTC by lukevalenty

2024-09-01 20:26 UTC, lukevalenty commented
Passes CI in our downstream repo. 😎

2024-09-03 20:20 UTC, bdeane-intel commented on include/flow/graph_builder.hpp
> +            constexpr auto missing_nodes_tuple = missing_nodes_tuple_t{};
**issue**: `missing_nodes_t` is already a tuple? (and the comment is wrong)

2024-09-03 20:20 UTC, bdeane-intel commented on include/flow/detail/walk.hpp
> +        if constexpr (std::remove_cvref_t<N>::is_reference) {
**thought**: I just noticed how odd this looks...

2024-09-03 20:20 UTC, bdeane-intel commented on include/flow/graph_builder.hpp
> +        });
**suggestion**: Move the `stdx::to_unsorted_set` from the `get_edges_t` overload of `tag_invoke` to `build`, then collapse all three overloads here to:
```cpp
friend constexpr auto tag_invoke(auto tag, graph const &g) {
  return g.fragments.apply([](auto const &...frags) {
      return stdx::tuple_cat(tag(frags)...);
  });
}
```

2024-09-03 20:42 UTC, lukevalenty commented on include/flow/detail/walk.hpp
> +        if constexpr (std::remove_cvref_t<N>::is_reference) {
anything we should do about it?

2024-09-03 20:46 UTC, bdeane-intel commented on include/flow/detail/walk.hpp
> +        if constexpr (std::remove_cvref_t<N>::is_reference) {
rename `is_reference` to `is_pointer`? :)

2024-09-03 20:47 UTC, bdeane-intel commented on include/flow/detail/walk.hpp
> +        if constexpr (std::remove_cvref_t<N>::is_reference) {
And find a name that doesn't quite clash with a `std` type_trait...

2024-09-03 20:48 UTC, lukevalenty commented on include/flow/detail/walk.hpp
> +        if constexpr (std::remove_cvref_t<N>::is_reference) {
Ohhh....yes, i see it now!

2024-09-04 17:51 UTC, elbeno commented on include/cib/detail/runtime_conditional.hpp
> +                        return make_runtime_conditional(Cond{}, Arg{});
**todo**: Provide a "poison pill" function template in this namespace that is found so that ADL can occur in all cases. (Consider making `make_runtime_conditional` a function object?)

2024-09-04 17:51 UTC, elbeno commented on include/cib/detail/runtime_conditional.hpp
> +    operator and(runtime_condition<RhsName, RhsPs...> rhs) const {
**suggestion**: Make this a free binary function

2024-09-04 17:51 UTC, elbeno commented on include/flow/detail/walk.hpp
> +concept subgraph = requires { typename stdx::remove_cvref_t<T>::is_subgraph; };
**suggestion**: Follow-up with beefing up this concept, and removing `tag_invoke`. I like the name change from `node` to `subgraph`.

2024-09-04 17:51 UTC, elbeno commented on include/flow/detail/walk.hpp
> +template <typename Source, typename Dest, typename Cond> struct edge {
**suggestion**: Expose a `cond_t` as well as the `source_t` and `dest_t`. (I know the condition is used by deducing/destructuring the type, but for consistency's sake...)

2024-09-04 17:53 UTC, lukevalenty commented on include/flow/detail/walk.hpp
> +                      subgraph_identity::REFERENCE) {
It started out like that, but some earlier versions of clang didn't like me using `n` in a constant expression :(

2024-09-04 21:16 UTC, lukevalenty commented on include/flow/detail/walk.hpp
> +concept subgraph = requires { typename stdx::remove_cvref_t<T>::is_subgraph; };
we'll do this in a follow-on PR

2024-09-09 19:09 UTC, mjcaisse-intel requested changes

2024-09-10 20:30 UTC, lukevalenty commented on docs/flows.adoc
> +The `*` operator is used to explicitly add an action to the
I need to write the documentation for core cib in order to do this since it's not specific to flows. I can do it as part of this PR, or another follow-on PR. It will take me some time.

2024-09-10 22:10 UTC, bdeane-intel commented on docs/flows.adoc
> +The `*` operator is used to explicitly add an action to the
I move to do that as a follow-up

2024-09-10 22:33 UTC, mjcaisse-intel approved these changes

2024-09-10 23:28 UTC, merged